# Numpy vs PyTorch

In [13]:
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [14]:
# Convert to numpy array
import numpy as np

np.array(arr)

array([[1, 2],
       [3, 4]])

In [15]:
# Convert to PyTorch tensor
import torch

torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

## Create matrices with default values

In [16]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [17]:
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [18]:
np.random.rand(2, 2)

array([[0.67680195, 0.90619991],
       [0.93735366, 0.31652634]])

In [21]:
torch.rand(2, 2)

tensor([[0.5729, 0.3452],
        [0.5914, 0.7761]])

## Seeds for reproducibility

Use seed to generate exact matrics

**Seed for GPU is different**

```
if torch.cuda.is_availabel():
    torch.cuda.manual_seed(0)
```

In [38]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [39]:
# Re-generate the exact matrics using seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [24]:
# No seed
np.random.rand(2, 2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [25]:
# Re-generate matrics without seed
np.random.rand(2, 2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [30]:
# pyTorch seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [29]:
# Re-generate the exact matrics using seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [34]:
# No seed
torch.rand(2, 2)

tensor([[0.6977, 0.8000],
        [0.1610, 0.2823]])

In [33]:
# Re-generate matrics without seed
torch.rand(2, 2)

tensor([[0.0223, 0.1689],
        [0.2939, 0.5185]])

## Bridge

### PyTorch to Numpy

In [44]:
np_arr = np.ones((2, 2))
print(np_arr)

[[1. 1.]
 [1. 1.]]


In [45]:
print(type(np_arr))

<class 'numpy.ndarray'>


In [46]:
# Convert numpy array to pyTorch Tensor
torch_tensor = torch.from_numpy(np_arr)
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [47]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [51]:
np_arr_new = np.ones((2, 2), dtype=np.int32)
torch.from_numpy(np_arr_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [52]:
np_arr_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_arr_new)

tensor([[1, 1],
        [1, 1]])

In [53]:
np_arr_new = np.ones((2, 2), dtype=np.double)
torch.from_numpy(np_arr_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

### Numpy to PyTorch