# Numpy vs PyTorch syntax compare

In [2]:
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [3]:
# Convert to numpy array
import numpy as np

np.array(arr)

array([[1, 2],
       [3, 4]])

In [4]:
# Convert to PyTorch tensor
import torch

torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

## Create matrices with default values

In [5]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [6]:
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [7]:
np.random.rand(2, 2)

array([[0.20301859, 0.57549504],
       [0.90573489, 0.31853932]])

In [8]:
torch.rand(2, 2)

tensor([[0.7844, 0.7613],
        [0.2677, 0.7815]])

## Seeds for reproducibility

Use seed to generate exact matrics

**Seed for GPU is different**

```
if torch.cuda.is_availabel():
    torch.cuda.manual_seed(0)
```

In [9]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [10]:
# Re-generate the exact matrics using seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [11]:
# No seed
np.random.rand(2, 2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [12]:
# Re-generate matrics without seed
np.random.rand(2, 2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [13]:
# pyTorch seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [14]:
# Re-generate the exact matrics using seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [15]:
# No seed
torch.rand(2, 2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

In [16]:
# Re-generate matrics without seed
torch.rand(2, 2)

tensor([[0.4556, 0.6323],
        [0.3489, 0.4017]])

## Bridge

### PyTorch to Numpy

In [17]:
np_arr = np.ones((2, 2))
print(np_arr)

[[1. 1.]
 [1. 1.]]


In [18]:
print(type(np_arr))

<class 'numpy.ndarray'>


In [19]:
# Convert numpy array to pyTorch Tensor
torch_tensor = torch.from_numpy(np_arr)
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [20]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [21]:
np_arr_new = np.ones((2, 2), dtype=np.int32)
torch.from_numpy(np_arr_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [22]:
np_arr_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_arr_new)

tensor([[1, 1],
        [1, 1]])

In [23]:
np_arr_new = np.ones((2, 2), dtype=np.double)
torch.from_numpy(np_arr_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

### Numpy to PyTorch

In [24]:
torch_tensor = torch.ones(2, 2)
type(torch_tensor)

torch.Tensor

In [25]:
torch_to_numpy = torch_tensor.numpy()
type(torch_to_numpy)

numpy.ndarray

## Tensor on CPU vs GPU

In [33]:
# By default Tensor created on CPU
tensor_cpu = torch.ones(2, 2)
tensor_cpu

tensor([[1., 1.],
        [1., 1.]])

In [31]:
# CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()
else:
    print("Currently only supports CPU, install Cuda to enable GPU for your models")

Currently only supports CPU, install Cuda to enable GPU for your models


In [32]:
# GPU to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])