# Tensor Operations

## Resizing Tensor

In [2]:
import torch

torch_tensor = torch.ones(2, 2)
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]])


In [3]:
print(torch_tensor.size())

torch.Size([2, 2])


In [4]:
torch_tensor.view(4)

tensor([1., 1., 1., 1.])

In [5]:
torch_tensor.view(4).size()

torch.Size([4])

## Element wise operations

In [6]:
a = torch.ones(2, 2)
print(a)

b = torch.ones(2, 2)
print(b)

c = a + b
print(c)

# OR

c = torch.add(a, b)
print(c)

# In-place addition
a.add_(b)
print(a)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])


In [7]:
a = torch.ones(2, 2)
print(a)

b = torch.ones(2, 2)
print(b)

c = a - b
print(c)

# OR

c = torch.sub(a, b)
print(c)

# In-place addition
a.sub_(b)
print(a)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


In [8]:
a = torch.ones(2, 2)
print(a)

b = torch.zeros(2, 2)
print(b)

c = a * b
print(c)

# OR

c = torch.mul(a, b)
print(c)

# In-place addition
a.mul_(b)
print(a)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


In [9]:
a = torch.ones(2, 2)
print(a)

b = torch.zeros(2, 2)
print(b)

c = b / a
print(c)

# OR

c = torch.div(b, a)
print(c)

# In-place addition
b.mul_(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


## Tensor mean

In [10]:
a = torch.Tensor([5, 25, 50, 100, 200, 400])
print(a.size())

a.mean(dim=0) # dimension

# a.mean(dim=1) # this will error out

torch.Size([6])


tensor(130.)

In [11]:
a = torch.Tensor([[5, 25, 50, 100, 200, 400], [5, 25, 50, 100, 200, 400]])
print(a.size())
a.mean(dim=1)

torch.Size([2, 6])


tensor([130., 130.])

##  Tensor Standard Deviation

In [13]:
a = torch.Tensor([5, 25, 50, 100, 200, 400])
a.std(dim=0) # dimension

tensor(149.4992)